Fix bug in build functions and move to functions-dev b/c not webrh specific

diff --git a/functions-dev b/functions-dev
--- a/functions-dev
+++ b/functions-dev
@@ -68,3 +68,62 @@ function topofrepo {
 	[[ $i -lt ${#arr[@]} ]] && root=$(IFS='/'; shift; echo "/${arr[*]:0:$i+1}") && cd $root
 	IFS=$oldIFS
 }
+
+function spin {
+    printf "\r${1}: [ ${sp:sc++:1} ] "
+    ((sc==${#sp})) && sc=0
+}
+
+function endspin {
+    printf "\r%s\n" "$@"
+}
+
+# Kick off a jenkins build
+function buildstatus {
+	sandbox=$(sandbox $1)
+    JOB_URL="${sandbox/root\@/http\:\/\/}:8080/job/webdrupal-update"
+    JOB_STATUS_URL=${JOB_URL}/lastBuild/api/json
+	GREP_RETURN_CODE=0
+	
+	# Test if url is accessible
+	test=$(curl -s --max-time 5 --head $JOB_STATUS_URL | head -n 1 | tr -d '[:space:]')
+	if [[ ${test: -2} == "OK" ]]; then
+		# Poll every thirty seconds until the build is finished
+	    while [ $GREP_RETURN_CODE -eq 0 ]; do
+	        spin "Please wait for the Jenkins build to finish"
+	        sleep 1
+
+	        # Grep will return 0 while the build is running:
+			status=$(curl -s $JOB_STATUS_URL | grep result\":null)
+			GREP_RETURN_CODE=$?
+	    done
+	    endspin
+		
+		success=$(curl -s $JOB_STATUS_URL | grep "result\":\"SUCCESS")
+		[ $? -eq 0 ] && echo "Build was successful!"
+		fail=$(curl -s $JOB_STATUS_URL | grep "result\":\"FAILURE")
+		[ $? -eq 0 ] && echo "Build failed :("
+	else
+		echo "Sandbox url is not available"
+	fi
+}
+
+function buildbox {
+	sandbox=$(sandbox $1)
+    JOB_URL="${sandbox/root\@/http\:\/\/}:8080/job/webdrupal-update"
+    JOB_STATUS_URL=${JOB_URL}/lastBuild/api/json
+    GREP_RETURN_CODE=0
+	
+	# Check if a build is already running
+	test=$(curl -s $JOB_STATUS_URL | grep result\":null)
+    
+	GREP_RETURN_CODE=$?
+	
+	[[ $GREP_RETURN_CODE == 0 ]] && read -e -p "It looks like a build is already running; are you sure you want to kick off another one? [y/n]" choice
+	
+    # Start the build
+	[[ $choice == "y" || $GREP_RETURN_CODE > 0 ]] && curl $JOB_URL/buildWithParameters?delay=0sec
+
+    # Poll every thirty seconds until the build is finished
+	buildstatus $1
+}
